/* Database schema to keep the structure of entire database. */

CREATE TABLE animals(
animal_id  int generated by default as identity,
animal_name  varchar(30) not null,
date_of_birth date not null,
escape_attempts int, 
neutered boolean ,
weight_kg decimal(4,2) not null
);
